### ISSUE TITLE
idea导入错误

### ISSUE THREAD

**Issue by MikaGuraN** [HyDevelop/PicqBotX#9]
找不到 : com.github.hykilpikonna:HyConfigLib:-1eb4f7896a-1

**Comment by MikaGuraN** [comment]
直接运行了报错
Exception in thread "main" java.lang.NoClassDefFoundError: cc/moecraft/yaml/utils/FileUtils
	at cc.moecraft.logger.environments.FileEnv.<init>(FileEnv.java:37)
	at cc.moecraft.logger.environments.FileEnv.<init>(FileEnv.java:58)
	at cc.moecraft.icq.PicqBotX.<init>(PicqBotX.java:82)
	at cc.moecraft.icq.PicqBotX.<init>(PicqBotX.java:74)

**Comment by MikaGuraN** [comment]
[18-07-22 15:46:43] [PicqBotX] [INFO] 日志管理器     初始化完成 [******] ...(0.18 ms)
[18-07-22 15:46:44] [PicqBotX] [INFO] 缓存管理器     初始化完成 [******] ...(6.28 ms)
[18-07-22 15:46:44] [PicqBotX] [INFO] DEBUG设置      初始化完成 [******] ...(0.02 ms)
[18-07-22 15:46:45] [PicqBotX] [INFO] 事件管理器     初始化完成 [******] ...(779.75 ms)
[18-07-22 15:46:45] [PicqBotX] [INFO] HTTP发送器     初始化完成 [******] ...(3.27 ms)
[18-07-22 15:46:45] [PicqBotX] [INFO] HTTP监听服务器 初始化完成 [******] ...(2.52 ms)
Exception in thread "main" com.xiaoleilu.hutool.http.HttpException: Connection refused: connect
	at com.xiaoleilu.hutool.http.HttpRequest.send(HttpRequest.java:697)
	at com.xiaoleilu.hutool.http.HttpRequest.execute(HttpRequest.java:569)
	at com.xiaoleilu.hutool.http.HttpRequest.execute(HttpRequest.java:545)
	at com.xiaoleilu.hutool.http.HttpUtil.post(HttpUtil.java:297)
	at cc.moecraft.icq.sender.IcqHttpApi.send(IcqHttpApi.java:99)
	at cc.moecraft.icq.sender.IcqHttpApi.sendReturnRaw(IcqHttpApi.java:121)
	at cc.moecraft.icq.sender.IcqHttpApi.sendReturnList(IcqHttpApi.java:168)
	at cc.moecraft.icq.sender.IcqHttpApi.sendReturnList(IcqHttpApi.java:180)
	at cc.moecraft.icq.sender.IcqHttpApi.getGroupList(IcqHttpApi.java:511)
	at 间.酷Q.机器人.取群列表(机器人.java:30)
	at 机器人实例.main(机器人实例.java:11)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at com.xiaoleilu.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:481)
	at com.xiaoleilu.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:718)
	at com.xiaoleilu.hutool.http.HttpRequest.send(HttpRequest.java:689)
	... 10 more
检测到进程关闭... 正在保存Log...

**Comment by hykilpikonna** [comment]
更新[v1.3.0.387](https://github.com/HyDevelop/PicqBotX/releases/tag/1.3.0.387)中已解决!<br>
